project:
  type: book
  output-dir: _book

book:
  title: "Kenya Statistical Production Model"
  author: "Kenya National Bureau of Statistics"
  date: "`r Sys.Date()`"
  chapters:
    - index.md
    - part: "Introduction"
      chapters:
        - Introduction/About KNBS.md
        - Introduction/GSBPM.md
        - Introduction/Supporting Frameworks.md
    - part: "Process 1: Specify Needs"
      chapters:
        - Process1/1.md
        - Process1/1.1.md
        - Process1/1.2.md
        - Process1/1.3.md
        - Process1/1.4.md
        - Process1/1.5.md
        - Process1/1.6.md
    - part: "Process 2: Design"
      chapters:
        - Process2/2.md
        - Process2/2.1.md
        - Process2/2.2.md
        - Process2/2.3.md
        - Process2/2.4.md
        - Process2/2.5.md
        - Process2/2.6.md
    - part: "Process 3: Build"
      chapters:
        - Process3/3.md
        - Process3/3.1.md
        - Process3/3.2.md
        - Process3/3.3.md
        - Process3/3.4.md
        - Process3/3.5.md
        - Process3/3.6.md
        - Process3/3.7.md
    - part: "Process 4: Collect"
      chapters:
        - Process4/4.md
        - Process4/4.1.md
        - Process4/4.2.md
        - Process4/4.3.md
        - Process4/4.4.md
    - part: "Process 5: Process"
      chapters:
        - Process5/5.md
        - Process5/5.1.md
        - Process5/5.2.md
        - Process5/5.3.md
        - Process5/5.4.md
        - Process5/5.5.md
        - Process5/5.6.md
        - Process5/5.7.md
        - Process5/5.8.md
    - part: "Process 6: Analyse"
      chapters:
        - Process6/6.md
        - Process6/6.1.md
        - Process6/6.2.md
        - Process6/6.3.md
        - Process6/6.4.md
        - Process6/6.5.md
    - part: "Process 7: Disseminate"
      chapters:
        - Process7/7.md
        - Process7/7.1.md
        - Process7/7.2.md
        - Process7/7.3.md
        - Process7/7.4.md
        - Process7/7.5.md
    - part: "Process 8: Evaluate"
      chapters:
        - Process8/8.md
        - Process8/8.1.md
        - Process8/8.2.md
        - Process8/8.3.md

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
